!-------------------------------------------------------------
! SET PRIMARY GRID DIMENSIONS AND PRESSURE OUTPUT LEVELS
      INTEGER,PARAMETER:: IM=IMIN,JM=JMIN,LM=LMIN,LSM=LSMIN
!-------------------------------------------------------------
! SET THE NUMBER OF PEs IN THE I-DIRECTION AND J-DIRECTION
      INTEGER,PARAMETER:: INPES=IPCIN,JNPES=JPCIN
!-------------------------------------------------------------
      INTEGER,PARAMETER:: IGSTL=-5,IGSTR=5
      INTEGER,PARAMETER:: JGSTL=-5,JGSTR=5
      INTEGER,PARAMETER:: ITAIL=IM-(INPES*(IM/INPES))
      INTEGER,PARAMETER:: JTAIL=JM-(JNPES*(JM/JNPES))

      INTEGER,PARAMETER:: IDIM1=IGSTL,IDIM2=IM/INPES+IGSTR+1
      INTEGER,PARAMETER:: JDIM1=JGSTL,JDIM2=JM/JNPES+JGSTR+1
