
.SUFFIXES :
.SUFFIXES : .F .f .c .o .a
.PRECIOUS : $(LIB)
.SILENT:

# Define system commands.

RM      = /bin/rm -f
ECHO    = /bin/echo
ARCHIVE = ar rs

# Define compiler flags from machine dependent make.inc.

include ../../configure/make.inc

INC       = ../../include
COMPILE.f = $(FC) -c $(FFLAGS) -I$(INC)

# Define all necessary source files.

OBJ = \
$(LIB)(conv_index.o)   $(LIB)(ecommons.o)   \
$(LIB)(postcommons.o)  $(LIB)(pqk.o)       $(LIB)(rtll.o)   

# Define library path and name.

#LIB = $(LIBDIR)/libetautil.a
LIB = ./libetautil.a
.f.a:
	$(ECHO)
	$(ECHO) "Compiling $<"
	$(COMPILE.f) $<
	$(ECHO) "Adding $(<:.f=.o) to $(LIB) archive HERE."
	$(ARCHIVE) $@ $(<:.f=.o)
	$(RM) $(<:.f=.o)

.f.o:
	$(ECHO)
	$(ECHO) "Compiling $<"
	$(COMPILE.f) $<
	$(ECHO) "Adding $(<:.f=.o) to $(LIB) archive."
	$(ARCHIVE) $(LIB) $(<:.f=.o)
	$(RM) $(<:.f=.o)

# Default target.

$(LIB): $(OBJ)
	$(ECHO)
	$(ECHO) "$(LIB) up-to-date"
	$(ECHO)

lib: $(LIB)

# Dependencies.

$(LIB)(ecommons.o)    : $(INC)/ecommons.h
$(LIB)(postcommons.o) : $(INC)/postcommons.h
$(LIB)(pqk.o)         : $(INC)/ecommons.h 

clean:
	/bin/rm -f *i.*.f*
