#!/bin/bash
function clrd(){
    local color=$1;
    local backgnd=$2;
    case $color in
        0) tput setaf 0 ;; # black
        1) tput setaf 1 ;; # red
        2) tput setaf 2 ;; # green
        3) tput setaf 3 ;; # yellow
        4) tput setaf 4 ;; # blue
        5) tput setaf 5 ;; # magenta
        6) tput setaf 6 ;; # cyan
        7) tput setaf 7 ;; # white
        *) tput sgr0;
    esac
    case $backgnd in
        0) tput setb 0 ;; # black
        1) tput setb 1 ;; # red
        2) tput setb 2 ;; # green
        3) tput setb 3 ;; # yellow
        4) tput setb 4 ;; # blue
        5) tput setb 5 ;; # magenta
        6) tput setb 6 ;; # cyan
        7) tput setb 7 ;; # white
    esac
}
#
#
tput clear
divider=================================
divider=$divider$divider$divider$divider$divider$divider$divider
width=`tput cols`

if (($#<1)) ; then
##################################
text="DEFINE ENVIRONMENT INSTALL"
##################################
lng=`expr length "${text}"`
printf "%$width.${width}s\n\v" "$divider"
printf "%`expr \( $width / 2 \) + \( $lng / 2 \)`s\n\v" "${text}"
printf "%$width.${width}s\n" "$divider"
text="OPTIONS:"
printf "%s\n" "$(clrd ${clr1})${text} ${msg1}$(clrd)"
Machines=`ls -d ../machines/*`
NumberOfMachines=`echo ${Machines}| wc -w`
for i in `basename -a ${Machines}`
do
 printf "%s\n" "   $(clrd ${clr1})${i} ${msg1}$(clrd)"
done
ltest="true"
while [ ${ltest} = "true" ] ;do
printf "%s" "Choose: "
read Machine
export ${Machine}
Occurrence=`echo ${Machines}|grep ${Machine}|wc -w`
if ((${Occurrence}>0));then
   ltest="false"
else
   echo "ERROR: '${Machine}': unknown input. "
   echo "Note: Case sensitive option!"
fi
done
else
  Machine=$1
fi

rm -f w3lib
rm -f iplib
rm -f bufrlib
rm -f ./dummyMPI/libmpi.a
rm -f ./dummyMPI/*.o

cd ./dummyMPI
if [ -s Makefile_${Machine} ] ; then
  make -f Makefile_${Machine}
else
  ###########################################################
  text="Makefile_${Machine} not found in dummyMPI directory!"
  ###########################################################
  lng=`expr length "${text}"`
  printf "%$width.${width}s\n\v" "$divider"
  printf "%`expr \( $width / 2 \) + \( $lng / 2 \)`s\n\v" "${text}"
  printf "%$width.${width}s\n" "$divider"
  exit 1
fi
#
cd ../w3lib-1.9.source
make clean
if [ -s Makefile_${Machine} ] ; then
  make -f Makefile_${Machine}
else
  ###################################################################
  text="Makefile_${Machine} not found in w3lib-1.9.source directory!"
  ###################################################################
  lng=`expr length "${text}"`
  printf "%$width.${width}s\n\v" "$divider"
  printf "%`expr \( $width / 2 \) + \( $lng / 2 \)`s\n\v" "${text}"
  printf "%$width.${width}s\n" "$divider"
  exit 1
fi
#
if [ -s ../configure/make.inc_${Machine} ] ; then
  cp ../configure/make.inc_${Machine} ../configure/make.inc
  cd ../iplib.source.le
  make
  cd ../ei_bufrlib.source
  make
else
  ###################################################################
  text="make.inc_${Machine} not found in ../configure directory!"
  ###################################################################
  lng=`expr length "${text}"`
  printf "%$width.${width}s\n\v" "$divider"
  printf "%`expr \( $width / 2 \) + \( $lng / 2 \)`s\n\v" "${text}"
  printf "%$width.${width}s\n" "$divider"
  exit 1
fi
exit 0
