!-------------------------------------------------------------
! SET PRIMARY GRID DIMENSIONS AND PRESSURE OUTPUT LEVELS
      INTEGER(KIND=I4KIND), PARAMETER :: IM  = 101
      INTEGER(KIND=I4KIND), PARAMETER :: JM  = 159
      INTEGER(KIND=I4KIND), PARAMETER :: LM  =  50
      INTEGER(KIND=I4KIND), PARAMETER :: LSM =  22
!-------------------------------------------------------------
! SET THE NUMBER OF PEs IN THE I-DIRECTION AND J-DIRECTION
      INTEGER(KIND=I4KIND), PARAMETER :: INPES = 1
      INTEGER(KIND=I4KIND), PARAMETER :: JNPES = 4
!-------------------------------------------------------------
      INTEGER(KIND=I4KIND), PARAMETER :: IGSTL = -5
      INTEGER(KIND=I4KIND), PARAMETER :: IGSTR =  5
      INTEGER(KIND=I4KIND), PARAMETER :: JGSTL = -5
      INTEGER(KIND=I4KIND), PARAMETER :: JGSTR =  5
!
      INTEGER(KIND=I4KIND), PARAMETER :: ITAIL = IM - (INPES * (IM / INPES))
      INTEGER(KIND=I4KIND), PARAMETER :: JTAIL = JM - (JNPES * (JM / JNPES))

      INTEGER(KIND=I4KIND), PARAMETER :: IDIM1 = IGSTL
      INTEGER(KIND=I4KIND), PARAMETER :: IDIM2 = IM / INPES + IGSTR + 1
      INTEGER(KIND=I4KIND), PARAMETER :: JDIM1 = JGSTL
      INTEGER(KIND=I4KIND), PARAMETER :: JDIM2 = JM / JNPES + JGSTR + 1
