    SUBROUTINE READ_OUT2RESTRT(TSTART)
!>--------------------------------------------------------------------------------------------------
!> SUBROUTINE READ_OUT2RESTRT
!>
!> SUBPROGRAM: READ_OUT2RESTRT - 
!>
!> DRIVER     : INIT
!>              INITS
!>
!>--------------------------------------------------------------------------------------------------
!    USE ABCI        !andre check
    USE ACMCLD      !andre check
    USE ACMCLH      !andre check
    USE ACMPRE      !andre check
    USE ACMRDL      !andre check
    USE ACMRDS      !andre check
    USE ACMSFC      !andre check
    USE ASTSAV      !andre check
    USE BANDTA      !andre check
    USE BDCOMB      !andre check
    USE BDWIDE      !andre check
    USE BOCO        !andre check
    USE BUFFER      !andre check
    USE C_FRACN     !andre check
    USE CLDWTR      !andre check
    USE CMICRO_CONS !andre check
    USE CMICRO_START!andre check
    USE CMICRO_STATS!andre check
    USE CMY600      !andre check  
    USE CNVCLD      !andre check
    USE CO2BD2      !andre check
    USE CO2BD3      !andre check
    USE CO2BD4      !andre check
    USE CO2BD5      !andre check
    USE COMPVS0     !andre check    
    USE COMPVS      !andre check
    USE CONTIN      !andre check   
    USE C_TADJ      !andre check    
    USE CTLBLK      !andre check
    USE CUINIT      !andre check
!    USE DIUCON      !andre check
    USE DYNAM       !andre check
!    USE MODULE EXCH_BUF_REAL!andre check
    USE F77KINDS
    USE GLB_TABLE   !andre check
    USE HCON
    USE IACCR_TABLES!andre check
    USE IMASS_TABLES!andre check
    USE INDX        !andre check
    USE INPUT       !andre check
    USE IRATE_TABLES!andre check
    USE IRIME_TABLES!andre check
    USE IVENT_TABLES!andre check
    USE LOOPS       !andre check
    USE MAPOT       !andre check
    USE MAPPINGS    !andre check
    USE MASKS       !andre check
    USE MOMENTO     !andre check
    USE MPPCOM
    USE NHYDRO      !andre check
    USE NSOILTYPE   !andre check
    USE OPTIONS     !andre check
!    USE OUTFIL      !andre check  
!    USE PHYCON      !andre check: all variables now are parameter 
    USE PHYS        !andre check 
    USE PPTASM      !andre check
    USE PRFHLD      !andre check
    USE PVRBLS      !andre check
    USE RACCR_TABLES!andre check
    USE RD1TIM      !andre check
    USE RDFSAV      !andre check
    USE RITE        !andre check
    USE RMASS_TABLES!andre check
    USE RRATE_TABLES!andre check   
    USE RVELR_TABLES!andre check   
    USE RVENT_TABLES!andre check
!    USE SAVMEM      !andre check
    USE SCRTCH      !andre check
    USE SDENS_TABLES!andre check
    USE SEASO3      !andre check
    USE SLOPES      !andre check
    USE SOIL        !andre check
    USE SSALB       !andre check
    USE SWRSAV      !andre check
    USE TABCOM
    USE TEMPV       !andre check
    USE TOPO        !andre check
    USE VRBLS       !andre check
    USE UPDT
    USE Z0EFFT      !andre check
!
    IMPLICIT NONE
!
    INTEGER(KIND=I4KIND)                                                                        ::&
    & ITAG,  LISTOUT 
!    
    REAL   (KIND=R4KIND)                                                                        ::&
    & TSTART
!
    CHARACTER(LEN=6)                                                                            ::&
    & C_NHRS     
!   
    CHARACTER(LEN=4)                                                                            ::&
    & C_MYPE     
!   
    CHARACTER(LEN=150)                                                                          ::&
    & OUTFILE 
!
    ITAG=TSTART
    WRITE(C_NHRS,'(I6.6)') ITAG  
!
    WRITE(C_MYPE,'(I4.4)') MYPE
!            
    OUTFILE = "OUT2RESTRT/OUT2RESTRT_"//C_MYPE//"."//C_NHRS
!
    LISTOUT=1001
!
    OPEN (UNIT=LISTOUT, FILE= TRIM(OUTFILE), FORM = 'UNFORMATTED')
!
!MODULE_ABCI
!         READ(LISTOUT) NSOLD
!         READ(LISTOUT) AI
!	 READ(LISTOUT) BI
!	 READ(LISTOUT) CI
!MODULE ACMCLD
	 READ(LISTOUT) NCLOD    
	 READ(LISTOUT) TCLOD      
	 READ(LISTOUT) NCFRCV
	 READ(LISTOUT) NCFRST
	 READ(LISTOUT) ACFRCV
	 READ(LISTOUT) ACFRST  
!MODULE_ACMCLH 
         READ(LISTOUT) NHEAT
         READ(LISTOUT) THEAT
         READ(LISTOUT) AVRAIN
         READ(LISTOUT) AVCNVC
         READ(LISTOUT) ARATIM
         READ(LISTOUT) ACUTIM
         READ(LISTOUT) TRAIN
         READ(LISTOUT) TCUCN 
!MODULE_ACMPRE
	 READ(LISTOUT) TPREC
         READ(LISTOUT) ACSNOW
         READ(LISTOUT) ACSNOM 
         READ(LISTOUT) SSROFF
         READ(LISTOUT) BGROFF 
!MODULE_ACMRDL
	 READ(LISTOUT) NRDLW
	 READ(LISTOUT) ARDLW
	 READ(LISTOUT) TRDLW
         READ(LISTOUT) RLWIN
         READ(LISTOUT) RLWOUT 
         READ(LISTOUT) RLWTOA 
         READ(LISTOUT) ALWIN
         READ(LISTOUT) ALWOUT
         READ(LISTOUT) ALWTOA 
         READ(LISTOUT) RLWTT 
!MODULE_ACMRDS
	 READ(LISTOUT) NRDSW 
	 READ(LISTOUT) ARDSW
	 READ(LISTOUT) TRDSW
         READ(LISTOUT) RSWIN 
         READ(LISTOUT) RSWOUT
         READ(LISTOUT) RSWTOA
         READ(LISTOUT) ASWIN
         READ(LISTOUT) ASWOUT
         READ(LISTOUT) ASWTOA
         READ(LISTOUT) RSWTT
!MODULE_ACMSFC
	 READ(LISTOUT) NSRFC
	 READ(LISTOUT) ASRFC
	 READ(LISTOUT) TSRFC
	 READ(LISTOUT) APHTIM
	 READ(LISTOUT) SFCSHX
	 READ(LISTOUT) SFCLHX  								
	 READ(LISTOUT) SUBSHX 
	 READ(LISTOUT) SNOPCX  								
	 READ(LISTOUT) SFCUVX 
	 READ(LISTOUT) SFCEVP  								
	 READ(LISTOUT) POTEVP  
	 READ(LISTOUT) POTFLX
!MODULE_ASTSAV
	 READ(LISTOUT) SOLC    
	 READ(LISTOUT) RSIN1
	 READ(LISTOUT) RCOS1
	 READ(LISTOUT) RCOS2
!MODULE_BANDTA
         READ(LISTOUT) ARNDM
	 READ(LISTOUT) BRNDM  
	 READ(LISTOUT) BETAD   
	 READ(LISTOUT) AP     
	 READ(LISTOUT) BP      
	 READ(LISTOUT) ATP    
	 READ(LISTOUT) BTP    
	 READ(LISTOUT) BANDLO
	 READ(LISTOUT) BANDHI
         READ(LISTOUT) AO3RND  
	 READ(LISTOUT) BO3RND
	 READ(LISTOUT) AB15
         READ(LISTOUT) ARNDM1
	 READ(LISTOUT) ARNDM2  							
         READ(LISTOUT) BRNDM1  
         READ(LISTOUT) BRNDM2  							
         READ(LISTOUT) AP1    
         READ(LISTOUT) AP2     							
         READ(LISTOUT) BP1    
         READ(LISTOUT) BP2     							
         READ(LISTOUT) ATP1   
         READ(LISTOUT) ATP2    							
         READ(LISTOUT) BTP1   
         READ(LISTOUT) BTP2    							
         READ(LISTOUT) BETAD1  
         READ(LISTOUT) BETAD2  							
         READ(LISTOUT) BANDL1  
         READ(LISTOUT) BANDL2  							
         READ(LISTOUT) BANDH1 
         READ(LISTOUT) BANDH2   
         READ(LISTOUT) ARNDM3  							
         READ(LISTOUT) BRNDM3  							
         READ(LISTOUT) AP3     							
         READ(LISTOUT) BP3     							
         READ(LISTOUT) ATP3    							
         READ(LISTOUT) BTP3    							
         READ(LISTOUT) BETAD3  							
         READ(LISTOUT) BANDL3  							
         READ(LISTOUT) BANDH3
!MODULE_BDCOMB
         READ(LISTOUT) IBAND
         READ(LISTOUT) ACOMB
         READ(LISTOUT) BCOMB
         READ(LISTOUT) BETACM
         READ(LISTOUT) APCM
         READ(LISTOUT) BPCM
         READ(LISTOUT) ATPCM
         READ(LISTOUT) BTPCM
         READ(LISTOUT) BDLOCM
         READ(LISTOUT) BDHICM
         READ(LISTOUT) AB15CM
         READ(LISTOUT) AO3CM 
         READ(LISTOUT) BO3CM
         READ(LISTOUT) BETINC
!MODULE_BDWIDE
         READ(LISTOUT) AWIDE  
         READ(LISTOUT) BWIDE  
         READ(LISTOUT) BETAWD 
         READ(LISTOUT) APWD   
         READ(LISTOUT) BPWD   
         READ(LISTOUT) ATPWD  
         READ(LISTOUT) BTPWD  
         READ(LISTOUT) BDLOWD 
         READ(LISTOUT) BDHIWD 
         READ(LISTOUT) BETINW 
         READ(LISTOUT) AB15WD 
         READ(LISTOUT) SKO2D  
         READ(LISTOUT) SKC1R	
         READ(LISTOUT) SKO3R
!MODULE_BOCO	 
	 READ(LISTOUT) PDB
	 READ(LISTOUT) TB
	 READ(LISTOUT) QB
	 READ(LISTOUT) UB
	 READ(LISTOUT) VB
	 READ(LISTOUT) Q2B
	 READ(LISTOUT) CWMB     
!MODULE_BUFFER
	 READ(LISTOUT) IP
	 READ(LISTOUT) BUF
!MODULE_C_FRACN
	 READ(LISTOUT) F_ICE	   									  
	 READ(LISTOUT) F_RAIN     									  
	 READ(LISTOUT) F_RIMEF
!MODULE_CLDWTR
	 READ(LISTOUT) CWM
	 READ(LISTOUT) LC
	 READ(LISTOUT) U00
	 READ(LISTOUT) SR
	 READ(LISTOUT) UL
!MODULE_CMICRO_CONS
	 READ(LISTOUT)	ABFR		  
	 READ(LISTOUT)	CBFR	
	 READ(LISTOUT) CIACW 
	 READ(LISTOUT)	CIACR	      
	 READ(LISTOUT) C_N0R0
	 READ(LISTOUT)	CN0R0	      
	 READ(LISTOUT) CN0R_DMRMIN
	 READ(LISTOUT)	CN0R_DMRMAX   
	 READ(LISTOUT) CRACW 
	 READ(LISTOUT)	CRAUT	      
	 READ(LISTOUT) ESW0  
	 READ(LISTOUT)	QAUT0	
	 READ(LISTOUT)	RFMAX	
	 READ(LISTOUT)	RHGRD	      
	 READ(LISTOUT) RQR_DR1
	 READ(LISTOUT)	RQR_DR2 
	 READ(LISTOUT)	RQR_DR3 
	 READ(LISTOUT)	RQR_DRMIN
	 READ(LISTOUT)	RQR_DRMAX
	 READ(LISTOUT) RR_DR1
	 READ(LISTOUT)	RR_DR2  
	 READ(LISTOUT)	RR_DR3  
	 READ(LISTOUT)	RR_DRMIN	  
	 READ(LISTOUT)	RR_DRMAX
!MODULE_CMICRO_START
         READ(LISTOUT)	MICRO_START
!MODULE_CMICRO_STATS
         READ(LISTOUT)	NSTATS
         READ(LISTOUT)	QMAX
         READ(LISTOUT)	QTOT
!MODULE_CMY600
         READ(LISTOUT)	MY_GROWTH
!MODULE_CNVCLD
         READ(LISTOUT)	CUPPT
	 READ(LISTOUT) CFRACL  
	 READ(LISTOUT) CFRACM 
	 READ(LISTOUT) CFRACH
!MODULE_CO2BD2
	 READ(LISTOUT)CO231
	 READ(LISTOUT)CO238
	 READ(LISTOUT)CDT31
	 READ(LISTOUT)CDT38
	 READ(LISTOUT)C2D31
	 READ(LISTOUT)C2D38
!MODULE_CO2BD3
	 READ(LISTOUT)CO251
	 READ(LISTOUT)CO258
	 READ(LISTOUT)CDT51
	 READ(LISTOUT)CDT58
	 READ(LISTOUT)C2D51
	 READ(LISTOUT)C2D58
	 READ(LISTOUT)CO2M51
	 READ(LISTOUT)CO2M58
	 READ(LISTOUT)CDTM51
	 READ(LISTOUT)CDTM58
	 READ(LISTOUT)C2DM51
	 READ(LISTOUT)C2DM58 
	 READ(LISTOUT)STEMP
	 READ(LISTOUT)GTEMP
!MODULE_CO2BD4
	 READ(LISTOUT) CO271
	 READ(LISTOUT) CO278
	 READ(LISTOUT) CDT71
	 READ(LISTOUT) CDT78
 	 READ(LISTOUT) C2D71
 	 READ(LISTOUT) C2D78
!MODULE_CO2BD5
         READ(LISTOUT) CO211
	 READ(LISTOUT) CO218
!MODULE_COMPVS0
         READ(LISTOUT) C1XPVS0
         READ(LISTOUT) C2XPVS0
         READ(LISTOUT) TBPVS0
!MODULE_COMPVS
         READ(LISTOUT) C1XPVS
         READ(LISTOUT) C2XPVS
         READ(LISTOUT) TBPVS
!MODULE_CONTIN
	 READ(LISTOUT) PDSL
         READ(LISTOUT) PDSLO
	 READ(LISTOUT) PSDT
	 READ(LISTOUT) RTOP
	 READ(LISTOUT) OMGALF
	 READ(LISTOUT) DIV
	 READ(LISTOUT) ETADT
!MODULE_C_TADJ
 	 READ(LISTOUT) T_ADJ
	 READ(LISTOUT) T_OLD
!MODULE_CTLBLK
 	 READ(LISTOUT) RUN 
 	 READ(LISTOUT) FIRST   
 	 READ(LISTOUT) RESTRT  
 	 READ(LISTOUT) SIGMA   
 	 READ(LISTOUT) NEST    
 	 READ(LISTOUT) SINGLRST
 	 READ(LISTOUT) SUBPOST
 	 READ(LISTOUT) IHRST   
 	 READ(LISTOUT) NFCST   
 	 READ(LISTOUT) NBC     
 	 READ(LISTOUT) LIST    
 	 READ(LISTOUT) IOUT    
 	 READ(LISTOUT) NTSD    
 	 READ(LISTOUT) NTSTM   
 	 READ(LISTOUT) NSTART  
 	 READ(LISTOUT) NTDDMP  
 	 READ(LISTOUT) NPREC	
 	 READ(LISTOUT) IDTAD	
 	 READ(LISTOUT) NBOCO	
 	 READ(LISTOUT) NSHDE	
 	 READ(LISTOUT) NCP	
 	 READ(LISTOUT) NPHS	
 	 READ(LISTOUT) NCNVC	
 	 READ(LISTOUT) NRADS	
 	 READ(LISTOUT) NRADL 
 	 READ(LISTOUT) IDAT
 	 READ(LISTOUT) DT
!MODULE_CUINIT
         READ(LISTOUT) CURAD
!MODULE_CUPARM, 
!         ONLY PARAMETER
!MODULE_DIUCON
!         READ(LISTOUT) SEASON
!         READ(LISTOUT) XXXX
!         READ(LISTOUT) JDNMC
!         READ(LISTOUT) FCSTDA
!         READ(LISTOUT) FJDNMC
!         READ(LISTOUT) TSLAG
!         READ(LISTOUT) RLAG
!         READ(LISTOUT) TIMIN
!         READ(LISTOUT) TPI 
!         READ(LISTOUT) HPI   
!         READ(LISTOUT) YEAR
!         READ(LISTOUT) DAY    
!         READ(LISTOUT) DHR
!         READ(LISTOUT) JTIME
!         READ(LISTOUT) DAZ
!MODULE_DYNAM
         READ(LISTOUT) PT
         READ(LISTOUT) R      
         READ(LISTOUT) DY
         READ(LISTOUT) CPGFV
         READ(LISTOUT) EN
         READ(LISTOUT) ENT   
         READ(LISTOUT) F4D
         READ(LISTOUT) F4Q   
         READ(LISTOUT) EF4T  
         READ(LISTOUT) AETA
         READ(LISTOUT) DETA  
         READ(LISTOUT) RDETA
         READ(LISTOUT) F4Q2  
         READ(LISTOUT) ETA   
         READ(LISTOUT) DFL
         READ(LISTOUT) EM 
         READ(LISTOUT) EMT
         READ(LISTOUT) DX  
         READ(LISTOUT) WPDAR 
         READ(LISTOUT) CPGFU
         READ(LISTOUT) CURV  
         READ(LISTOUT) FCP   
         READ(LISTOUT) FDIV  
         READ(LISTOUT) F     
         READ(LISTOUT) DDMPU 
         READ(LISTOUT) DDMPV 
         READ(LISTOUT) FAD
!MODULE_EXCH_BUF_REAL
!         READ(LISTOUT) BUF0
!         READ(LISTOUT) BUF1
!         READ(LISTOUT) BUF2
!         READ(LISTOUT) BUF3
!MODULE_GLB_TABLE
         READ(LISTOUT) IS_GLB_TABLE
         READ(LISTOUT) IE_GLB_TABLE    
         READ(LISTOUT) JS_GLB_TABLE
         READ(LISTOUT) JE_GLB_TABLE
!MODULE_HCON
!MODULE_IACCR_TABLES
         READ(LISTOUT) ACCRI
!MODULE_IMASS_TABLES
         READ(LISTOUT) MASSI
!MODULE_INDX
!         READ(LISTOUT)IHE
!         READ(LISTOUT)IVE
!         READ(LISTOUT)IHW
!         READ(LISTOUT)IHW
!         READ(LISTOUT)IRAD
!         READ(LISTOUT)IHEG
!         READ(LISTOUT)IVEG
!         READ(LISTOUT)IHWG
!         READ(LISTOUT)IVWG
!         READ(LISTOUT)IRADG
!MODULE_INPUT
         READ(LISTOUT) ICH     
         READ(LISTOUT) ICM     
         READ(LISTOUT) ICT     
         READ(LISTOUT) ICB
         READ(LISTOUT) CH      
         READ(LISTOUT) CM      
         READ(LISTOUT) CL      
         READ(LISTOUT) EMCH    
         READ(LISTOUT) EMCM    
         READ(LISTOUT) EMCL
         READ(LISTOUT) RR      
         READ(LISTOUT) QQO3
         READ(LISTOUT) DTEMP   
         READ(LISTOUT) PPRESS 
!MODULE_IRATE_TABLES
         READ(LISTOUT) VSNOWI
!MODULE_IRIME_TABLES
         READ(LISTOUT) VEL_RF
!MODULE_IVENT_TABLES	 
         READ(LISTOUT) VENTI1
         READ(LISTOUT) VENTI2	 
!MODULE_LOOPS	 
	 READ(LISTOUT) IHLA
	 READ(LISTOUT) IHHA
	 READ(LISTOUT) IVLA
	 READ(LISTOUT) IVHA
	 READ(LISTOUT) JRA	 
	 READ(LISTOUT) LMH
	 READ(LISTOUT) LMV
!MODULE MAPOT
         READ(LISTOUT) LSL
         READ(LISTOUT) IXM
	 READ(LISTOUT) IYM
         READ(LISTOUT) ISHDE
         READ(LISTOUT) TSPH
         READ(LISTOUT) WBD
         READ(LISTOUT) SBD
         READ(LISTOUT) TLM0D
         READ(LISTOUT) TPH0D
         READ(LISTOUT) DLMD
	 READ(LISTOUT) DPHD
         READ(LISTOUT) CMLD
         READ(LISTOUT) DP30
         READ(LISTOUT) X1P
         READ(LISTOUT) Y1P
         READ(LISTOUT) DISLP
         READ(LISTOUT) Z0SLP
 	 READ(LISTOUT) SPL		 
	 READ(LISTOUT) ALSL 
	 READ(LISTOUT) TSHDE
	 READ(LISTOUT) ERLAM0 
	 READ(LISTOUT) CPHI0	 	 
	 READ(LISTOUT) SPHI0
!MODULE_MAPPINGS
	 READ(LISTOUT) G2LI    
	 READ(LISTOUT) L2GI
	 READ(LISTOUT) G2LJ
	 READ(LISTOUT) L2GJ
!MODULE_MASKS
	 READ(LISTOUT) VBM2    
	 READ(LISTOUT) VBM3    
	 READ(LISTOUT) SM      
	 READ(LISTOUT) SICE    
	 READ(LISTOUT) HBM2    
	 READ(LISTOUT) HBM3
	 READ(LISTOUT) HTM     
	 READ(LISTOUT) VTM
!MODULE_MOMENTO
	 READ(LISTOUT) UMFLX
	 READ(LISTOUT) VMFLX  
	 READ(LISTOUT) AKMS10
!MODULE_MPPCOM
         !colocar depois
!MODULE_NHYDRO
 	 READ(LISTOUT) HYDRO
 	 READ(LISTOUT) SPLINE	 
 	 READ(LISTOUT) DWDT
 	 READ(LISTOUT) PDWDT
 	 READ(LISTOUT) PINT	 
 	 READ(LISTOUT) W
 	 READ(LISTOUT) Z
!MODULE_NSOILTYPE
 	 READ(LISTOUT) NSOTYP
!MODULE_OPTIONS
 	 READ(LISTOUT) SPVAL
 	 READ(LISTOUT) IBESSL
 	 READ(LISTOUT) KSB     
 	 READ(LISTOUT) IOFFS   
 	 READ(LISTOUT) IFLAG   
 	 READ(LISTOUT) SATDEL
!MODULE_OUTFIL
! 	 READ(LISTOUT) RSTFIL
! 	 READ(LISTOUT) ITAG   
! 	 READ(LISTOUT) LRSTRT
!MODULE_PHYCON
!	 READ(LISTOUT) AMOLWT  
!	 READ(LISTOUT) CSUBP   
!	 READ(LISTOUT) DIFFCTR 
!	 READ(LISTOUT) G       
!	 READ(LISTOUT) GRAVDR  
!	 READ(LISTOUT) O3DIFCTR
!	 READ(LISTOUT) P0      
!	 READ(LISTOUT) P0XZP2  
!	 READ(LISTOUT) P0XZP8  
!	 READ(LISTOUT) P0X2    
!	 READ(LISTOUT) RADCON  
!	 READ(LISTOUT) RGAS    
!	 READ(LISTOUT) RGASSP  
!	 READ(LISTOUT) SECPDA  
!	 READ(LISTOUT) RATCO2MW
!	 READ(LISTOUT) RATH2OMW 								      
!	 READ(LISTOUT) RADCON1  								      
!	 READ(LISTOUT) GINV    
!	 READ(LISTOUT) P0INV   
!	 READ(LISTOUT) GP0INV
!MODULE_PHYS
 	 READ(LISTOUT) KTM
 	 READ(LISTOUT) DTQ2    
 	 READ(LISTOUT) TDTQ2   
 	 READ(LISTOUT) DTD     
 	 READ(LISTOUT) TDTD    		   
 	 READ(LISTOUT) ROS     
 	 READ(LISTOUT) CS      
 	 READ(LISTOUT) DS      
 	 READ(LISTOUT) ROI     
 	 READ(LISTOUT) CI      
 	 READ(LISTOUT) DI      		   
 	 READ(LISTOUT) PL      
 	 READ(LISTOUT) THL     
 	 READ(LISTOUT) RDQ     
 	 READ(LISTOUT) RDTH    
 	 READ(LISTOUT) RDP     
 	 READ(LISTOUT) RDTHE   		   
 	 READ(LISTOUT) PLQ     
 	 READ(LISTOUT) RDPQ    
 	 READ(LISTOUT) RDTHEQ
 	 READ(LISTOUT) DFRLG
 	 READ(LISTOUT) QS0     
 	 READ(LISTOUT) SQS
 	 READ(LISTOUT) THE0    
 	 READ(LISTOUT) STHE
 	 READ(LISTOUT) THE0Q   
 	 READ(LISTOUT) STHEQ
 	 READ(LISTOUT) MXSNAL  
 	 READ(LISTOUT) EPSR	    				 
 	 READ(LISTOUT) RADIN
 	 READ(LISTOUT) RADOT	    				 
 	 READ(LISTOUT) GLAT
 	 READ(LISTOUT) GLON	    				 
 	 READ(LISTOUT) CZEN	    				 
 	 READ(LISTOUT) HTOP
 	 READ(LISTOUT) HBOT	    				 
 	 READ(LISTOUT) CNVTOP 
 	 READ(LISTOUT) CNVBOT      				 
 	 READ(LISTOUT) TG
 	 READ(LISTOUT) GFFC	    				 
 	 READ(LISTOUT) SST
 	 READ(LISTOUT) ALBASE      				 
 	 READ(LISTOUT) ALBEDO      				 
 	 READ(LISTOUT) HDAC
 	 READ(LISTOUT) HDACV	    				 
 	 READ(LISTOUT) CZMEAN 
 	 READ(LISTOUT) SIGT4
 	 READ(LISTOUT) PTBL
 	 READ(LISTOUT) TTBL
 	 READ(LISTOUT) TTBLQ
!MODULE_PPTASM
 	 READ(LISTOUT) MTSTPE  
 	 READ(LISTOUT) ITSTLOC 
 	 READ(LISTOUT) JTSTLOC 
 	 READ(LISTOUT) PHOUR   								     
 	 READ(LISTOUT) APREC
 	 READ(LISTOUT) TLATCU  								     
 	 READ(LISTOUT) TLATGS
 	 READ(LISTOUT) PPTDAT
!MODULE_PRFHLD
 	 READ(LISTOUT) TLMIN  
 	 READ(LISTOUT) TLMAX 
!MODULE_PVRBLS  
 	 READ(LISTOUT) Z0
 	 READ(LISTOUT) USTAR
 	 READ(LISTOUT) UZ0 
 	 READ(LISTOUT) VZ0 
 	 READ(LISTOUT) THZ0   
 	 READ(LISTOUT) QZ0   
 	 READ(LISTOUT) THS
 	 READ(LISTOUT) QS
 	 READ(LISTOUT) AKMS 
 	 READ(LISTOUT) AKHS 
 	 READ(LISTOUT) RF
 	 READ(LISTOUT) TWBS 
 	 READ(LISTOUT) QWBS 
 	 READ(LISTOUT) SNO 
 	 READ(LISTOUT) SI
 	 READ(LISTOUT) CLDEFI 
 	 READ(LISTOUT) PREC
 	 READ(LISTOUT) ACPREC    
 	 READ(LISTOUT) ACCLIQ
 	 READ(LISTOUT) CUPREC
 	 READ(LISTOUT) TH100
 	 READ(LISTOUT) Q100
 	 READ(LISTOUT) U100
 	 READ(LISTOUT) V100
 	 READ(LISTOUT) TH10    
 	 READ(LISTOUT) Q10     
 	 READ(LISTOUT) U10
 	 READ(LISTOUT) V10
 	 READ(LISTOUT) TSHLTR
 	 READ(LISTOUT) TSHLTR1
 	 READ(LISTOUT) QSHLTR
 	 READ(LISTOUT) PSHLTR    
 	 READ(LISTOUT) XMOMFLUX
 	 READ(LISTOUT) YMOMFLUX
	 READ(LISTOUT) AKM10 
	 READ(LISTOUT) AKM10V 
!	 READ(LISTOUT) PLM     
         READ(LISTOUT) Q2   
!MODULE_RACCR_TABLES    
         READ(LISTOUT) ACCRR
!MODULE_RD1TIM
         READ(LISTOUT) K400
         READ(LISTOUT) RAD1
         READ(LISTOUT) CTHK
         READ(LISTOUT) TAUCV
         READ(LISTOUT) PTOPC
         READ(LISTOUT) LTOP
         READ(LISTOUT) LVL
!MODULE_RDFSAV
         READ(LISTOUT) EMISP   
         READ(LISTOUT) EMIST   
         READ(LISTOUT) XLATT   
         READ(LISTOUT) XLATP   
         READ(LISTOUT) Q19001  
         READ(LISTOUT) HP98    
         READ(LISTOUT) H3M6    
         READ(LISTOUT) HP75    
         READ(LISTOUT) H6M2    
         READ(LISTOUT) HP537   
         READ(LISTOUT) H74E1   
         READ(LISTOUT) H15E1   
         READ(LISTOUT) Q14330  
         READ(LISTOUT) HP2     
         READ(LISTOUT) TWENTY  
         READ(LISTOUT) HNINE   
         READ(LISTOUT) DEGRAD  
         READ(LISTOUT) HSIGMA 
         READ(LISTOUT) DAYSEC  
         READ(LISTOUT) RCO2
         READ(LISTOUT) CAO3SW  
         READ(LISTOUT) CAH2SW  
         READ(LISTOUT) CBSW
!MODULE_RITE
!         READ(LISTOUT) BETA    
!         READ(LISTOUT) DRIP    
!         READ(LISTOUT) EC      
!         READ(LISTOUT) EDIR    
!         READ(LISTOUT) ETT     
!         READ(LISTOUT) FLX1    
!         READ(LISTOUT) FLX2    
!         READ(LISTOUT) FLX3    
!         READ(LISTOUT) RUNOF   
!         READ(LISTOUT) DEW     
!         READ(LISTOUT) RIB     
!         READ(LISTOUT) RUNOFF3
!MODULE_RMASS_TABLES
         READ(LISTOUT) MASSR
!MODULE_RRATE_TABLES
         READ(LISTOUT) RRATE
!MODULE_RVELR_TABLES
         READ(LISTOUT) VRAIN
!MODULE_RVENT_TABLES
         READ(LISTOUT) VENTR1
         READ(LISTOUT) VENTR2
!MODULE_SAVEMEM
!         READ(LISTOUT) DDUO3N
!         READ(LISTOUT) DDO3N2  
!         READ(LISTOUT) DDO3N3  
!         READ(LISTOUT) DDO3N4
!         READ(LISTOUT) RAD1   ! aparece tambem no modulo RD1TIM    
!         READ(LISTOUT) RAD2    
!         READ(LISTOUT) RAD3    
!         READ(LISTOUT) RAD4
!MODULE_SCRTCH
         READ(LISTOUT) SUM    
	 READ(LISTOUT) PERTSM 
	 READ(LISTOUT) SUM3   
	 READ(LISTOUT) SUMWDE
         READ(LISTOUT) SRCWD
         READ(LISTOUT) SRC1NB 
         READ(LISTOUT) DBDTNB
         READ(LISTOUT) ZMASS  
	 READ(LISTOUT) ZROOT
         READ(LISTOUT) SC     
         READ(LISTOUT) DSC    
         READ(LISTOUT) XTEMV
         READ(LISTOUT) TFOUR
         READ(LISTOUT) FORTCU
         READ(LISTOUT) X     
         READ(LISTOUT) X1
         READ(LISTOUT) SRCS 
         READ(LISTOUT) SUM4 
         READ(LISTOUT) SUM6
         READ(LISTOUT) SUM7	
	 READ(LISTOUT) SUM8	
	 READ(LISTOUT) SUM4WD  
	 READ(LISTOUT) R1  	 
         READ(LISTOUT) R2	
         READ(LISTOUT) S2	
         READ(LISTOUT) T3   
         READ(LISTOUT) R1WD
	 READ(LISTOUT) X2	
         READ(LISTOUT) EXPO	
         READ(LISTOUT) FAC
         READ(LISTOUT) CNUSB	
         READ(LISTOUT) DNUSB
         READ(LISTOUT) ALFANB  
         READ(LISTOUT) AROTNB
         READ(LISTOUT) ANB	
         READ(LISTOUT) BNB	
         READ(LISTOUT) CENTNB  
         READ(LISTOUT) DELNB	
         READ(LISTOUT) BETANB
!MODULE_SDENS_TABLES
         READ(LISTOUT) SDENS
!MODULE_SEASO3
	 READ(LISTOUT) XDUO3N
	 READ(LISTOUT) XDO3N2
	 READ(LISTOUT) XDO3N3
	 READ(LISTOUT) XDO3N4
	 READ(LISTOUT) PRGFDL
	 READ(LISTOUT) O3O3
	 READ(LISTOUT) XRAD1
	 READ(LISTOUT) XRAD2
	 READ(LISTOUT) XRAD3
	 READ(LISTOUT) XRAD4
!MODULE_SLOPES
         READ(LISTOUT) ISLD
         READ(LISTOUT) VTMS 
!MODULE_SOIL	  
         READ(LISTOUT) IVGTYP 
         READ(LISTOUT) ISLTYP 
	 READ(LISTOUT) ISLOPE
         READ(LISTOUT) SOILTB
         READ(LISTOUT) SFCEXC
	 READ(LISTOUT) SMSTAV
	 READ(LISTOUT) SMSTOT
         READ(LISTOUT) GRNFLX 
         READ(LISTOUT) PCTSNO
         READ(LISTOUT) VEGFRC 
         READ(LISTOUT) CMC
	 READ(LISTOUT) SMC
	 READ(LISTOUT) STC
	 READ(LISTOUT) SH2O
	 READ(LISTOUT) SLDPTH
	 READ(LISTOUT) RTDPTH	 
!MODULE_SSALB	 
	 READ(LISTOUT) ZA
	 READ(LISTOUT) TRN
	 READ(LISTOUT) DZA
	 READ(LISTOUT) ALBD
	 READ(LISTOUT) ALB1
	 READ(LISTOUT) ALB2
	 READ(LISTOUT) ALB3	 
!MODULE_SWRSAV 
	 READ(LISTOUT) ABCFF
	 READ(LISTOUT) PWTS
	 READ(LISTOUT) CFCO2  
	 READ(LISTOUT) CFO3   
	 READ(LISTOUT) REFLO3 
	 READ(LISTOUT) RRAYAV
!MODULE_TABCOM
         !colocar depois
!MODULE_TEMPV
         READ(LISTOUT) P0
         READ(LISTOUT) T0
	 READ(LISTOUT) Q0
!MODULE_TOPO
         READ(LISTOUT) TEMP2X
         READ(LISTOUT) TTVG
	 READ(LISTOUT) HTMG
!MODULE_VRBLS
         READ(LISTOUT) PD
         READ(LISTOUT) FIS
         READ(LISTOUT) RES
         READ(LISTOUT) T
         READ(LISTOUT) U
         READ(LISTOUT) V
         READ(LISTOUT) Q
!MODULE_UPDT
         !colocar depois
!MODULE_Z0EFFT
	 READ(LISTOUT) ZEFFIJ
!
	 CLOSE(LISTOUT)
!--------------------------------------------------- 
! DONE READING INITIAL CONDITIONS OR A RESTART FILE.
!---------------------------------------------------
!
!------------------------------ 
! END OF SUBROUTINE READ_RESTRT
!------------------------------ 
    IF (MYPE == 0) THEN
        WRITE(*,*) 'INIT:  EXIT READ_OU2RESTRT'
        WRITE(*,*) ' '
    END IF
!
    RETURN
!
    END SUBROUTINE READ_OUT2RESTRT



